# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "MAC0214"
description:        "Blog para o progresso de MAC0214 no primeiro semestre de 2017"

# URL
baseurl:            ""
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "//kiko.gfjaru.com/about"
  - name:           "Download"
    href:           "//github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
